### ISSUE TITLE
Cannot Configure Endpoint with 'Cookie' Header

### ISSUE THREAD

**Issue by rafaelfiume** [mrak/stubby4net#13]
We are trying to ensure that our http client is sending the right request, which includes a 'Cookie' header, but it doesn't seem to work.

Here's an example:

```
- request:
    url: /startup
    method: POST
    query:
        journeyId: 0b19fe25
    headers:
      Content-Type: application/json
      Cookie: a_content_here
  response:
    status: 200
    headers:
      Content-Type: application/json
    body : >
        {
          "value" : "grapes"
        }
```

Whenever we try to invoke this endpoint, we get a 404 - unless we remove the 'Cookie' from the headers config. Are we missing something, or is this a bug?

Thanks in advance.
